"""Add A/B test models for user mode tracking and surveys

Revision ID: 3d221d84465c
Revises: 64733d9788f7
Create Date: 2025-09-25 15:55:14.344609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3d221d84465c'
down_revision: Union[str, None] = '64733d9788f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if tables already exist before creating them
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Skip if tables already exist
    if 'ab_test_sessions' in existing_tables:
        return
    
    # Ensure ENUM type exists (fresh DB에서는 아직 없을 수 있음)
    # NOTE: create_type=False 로 참조하고 있기 때문에, 여기서 안전하게 생성해둔다.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usermodetype') THEN
                CREATE TYPE usermodetype AS ENUM ('agent', 'freepass');
            END IF;
        END
        $$;
        """
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_mode', postgresql.ENUM('agent', 'freepass', name='usermodetype', create_type=False), nullable=False),
    sa.Column('session_started_at', sa.DateTime(), nullable=False),
    sa.Column('session_ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('overall_satisfaction', sa.Integer(), nullable=True),
    sa.Column('response_quality', sa.Integer(), nullable=True),
    sa.Column('response_speed', sa.Integer(), nullable=True),
    sa.Column('learning_effectiveness', sa.Integer(), nullable=True),
    sa.Column('positive_feedback', sa.Text(), nullable=True),
    sa.Column('negative_feedback', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_sessions_id'), 'ab_test_sessions', ['id'], unique=False)
    op.create_table('ab_test_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_session_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('response_time_seconds', sa.Float(), nullable=True),
    sa.Column('question_asked_at', sa.DateTime(), nullable=True),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('question_complexity', sa.Integer(), nullable=True),
    sa.Column('response_accuracy', sa.Integer(), nullable=True),
    sa.Column('response_clarity', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('clarifications_needed', sa.Integer(), nullable=True),
    sa.Column('follow_up_questions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_sessions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ab_test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_interactions_id'), 'ab_test_interactions', ['id'], unique=False)
    op.create_table('ab_test_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('overall_experience', sa.Integer(), nullable=False),
    sa.Column('ease_of_use', sa.Integer(), nullable=False),
    sa.Column('response_quality', sa.Integer(), nullable=False),
    sa.Column('response_speed', sa.Integer(), nullable=False),
    sa.Column('learning_effectiveness', sa.Integer(), nullable=False),
    sa.Column('preferred_mode', postgresql.ENUM('agent', 'freepass', name='usermodetype', create_type=False), nullable=True),
    sa.Column('mode_comparison_rating', sa.Integer(), nullable=True),
    sa.Column('best_features', sa.Text(), nullable=True),
    sa.Column('worst_features', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Integer(), nullable=True),
    sa.Column('would_use_again', sa.Integer(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('survey_completed_at', sa.DateTime(), nullable=True),
    sa.Column('survey_duration_minutes', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ab_test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_surveys_id'), 'ab_test_surveys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ab_test_surveys_id'), table_name='ab_test_surveys')
    op.drop_table('ab_test_surveys')
    op.drop_index(op.f('ix_ab_test_interactions_id'), table_name='ab_test_interactions')
    op.drop_table('ab_test_interactions')
    op.drop_index(op.f('ix_ab_test_sessions_id'), table_name='ab_test_sessions')
    op.drop_table('ab_test_sessions')
    
    # Drop ENUM type safely
    try:
        op.execute("DROP TYPE IF EXISTS usermodetype")
    except Exception:
        # ENUM doesn't exist or can't be dropped, ignore error
        pass
    # ### end Alembic commands ###
