"""Add SessionMessage model for MAICE Agent conversations

Revision ID: a799e9e22959
Revises: 20250107_add_google_oauth_fields
Create Date: 2025-09-11 02:26:14.437635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a799e9e22959'
down_revision: Union[str, None] = '20250107_add_google_oauth_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SessionMessage 테이블이 이미 존재하는지 확인
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    existing_tables = inspector.get_table_names()
    
    if 'session_messages' not in existing_tables:
        # SessionMessage 테이블 생성
        op.create_table('session_messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('conversation_session_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('sender', sa.String(length=20), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('message_type', sa.String(length=50), nullable=False),
            sa.Column('parent_message_id', sa.Integer(), nullable=True),
            sa.Column('request_id', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_sessions.id'], ),
            sa.ForeignKeyConstraint(['parent_message_id'], ['session_messages.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        
        # 인덱스 생성
        op.create_index('idx_session_messages_session_id', 'session_messages', ['conversation_session_id'])
        op.create_index('idx_session_messages_created_at', 'session_messages', ['created_at'])
        op.create_index('idx_session_messages_sender', 'session_messages', ['sender'])
        op.create_index('idx_session_messages_type', 'session_messages', ['message_type'])
        op.create_index('idx_session_messages_parent', 'session_messages', ['parent_message_id'])
        
        print("✅ session_messages 테이블 생성 완료")
    else:
        print("ℹ️ session_messages 테이블이 이미 존재합니다. 건너뜁니다.")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 인덱스 삭제
    op.drop_index('idx_session_messages_parent', table_name='session_messages')
    op.drop_index('idx_session_messages_type', table_name='session_messages')
    op.drop_index('idx_session_messages_sender', table_name='session_messages')
    op.drop_index('idx_session_messages_created_at', table_name='session_messages')
    op.drop_index('idx_session_messages_session_id', table_name='session_messages')
    
    # 테이블 삭제
    op.drop_table('session_messages')
    
    # ### end Alembic commands ###
